services:
  app:
    image: ${DOCKER_IMAGE:-sonej/gundaero-alley-api:latest}
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Dspring.profiles.active=prod -Duser.timezone=${TZ:-Asia/Seoul}
