server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework
  shutdown: graceful

spring:
  application:
    name: gundaero-alley-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jackson:
    time-zone: Asia/Seoul

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

# MyBatis 공통
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'NULL'
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath*:mapper/**/*.xml
  #type-aliases-package: com.gundaero.alley.domain

# 외부 서비스 프로퍼티 바인딩
kakao:
  adminKey: ${KAKAO_ADMIN_KEY:}

tourapi:
  base-url: ${TOURAPI_BASE_URL:https://apis.data.go.kr/B551011/KorService2}
  app-name: ${TOURAPI_APP_NAME:GEUNDAERO}
  service-key: ${TOURAPI_SERVICE_KEY:}

# CORS 허용 오리진()
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  cache:
    disabled: true

#upload:
#  max-size: 5242880 # 5MB
#  allowed-ext: jpg,jpeg,png
#  put-ttl-sec: 300
#  get-ttl-sec: 300


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.web.servlet: DEBUG
    org.apache.coyote.http11: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"