server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework
  shutdown: graceful

spring:
  application:
    name: gundaero-alley-api

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/appdb?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Seoul}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 10000

  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}

# Swagger/OpenAPI (prod에서는 OFF)
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# 로깅
logging:
  level:
    org.mybatis: INFO
    com.gundaero.alley.mapper: INFO

# JWT
jwt:
  secret: ${JWT_SECRET}
  access-ttl: ${JWT_ACCESS_TOKEN_TTL:900}
  refresh-ttl: ${JWT_REFRESH_TOKEN_TTL:1209600}

# S3
aws:
  s3:
    bucket: ${S3_BUCKET}
    region: ${S3_REGION:ap-northeast-2}
