server:
  port: ${SERVER_PORT:8080}
  # Nginx가 넘겨주는 X-Forwarded-* 헤더를 신뢰해서 'https' 판단하게 함
  forward-headers-strategy: framework
  shutdown: graceful

spring:
  application:
    name: gundaero-alley-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  lifecycle:
    timeout-per-shutdown-phase: 30s
  jackson:
    time-zone: Asia/Seoul

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

# CorsConfig에서 읽어갈 값
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
