server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework
  shutdown: graceful

spring:
  application:
    name: gundaero-alley-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/appdb?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Seoul}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # t4g.small 기준으로 가벼운 값
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000      # 5분
      max-lifetime: 600000      # 10분
      connection-timeout: 20000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

# 운영은 도메인 기반 CORS만 허용(실제 도메인으로 .env에서 주입)
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://gundaero.kozow.com}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

jwt:
  secret: ${JWT_SECRET}
  access-ttl: ${JWT_ACCESS_TOKEN_TTL:900}
  refresh-ttl: ${JWT_REFRESH_TOKEN_TTL:1209600}

aws:
  s3:
    bucket: ${S3_BUCKET}
    region: ${S3_REGION:ap-northeast-2}
