server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework
  shutdown: graceful

spring:
  application:
    name: gundaero-alley-api
  datasource:
    url: jdbc:mysql://localhost:3306/geundae?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.gundaero.alley.**.entity
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

jwt:
  token:
    secret:
      key: ${JWT_SECRET:dev-secret}
  secret: ${JWT_SECRET:dev-secret}

  access:
    token:
      expiration:
        seconds: ${JWT_ACCESS_TOKEN_TTL:900}
  refresh:
    token:
      expiration:
        seconds: ${JWT_REFRESH_TOKEN_TTL:1209600}
aws:
  s3:
    bucket: ${S3_BUCKET:gundaero-alley-prod-bucket}
    region: ${S3_REGION:ap-northeast-2}

kakao:
  client-id:        ${KAKAO_CLIENT_ID:}
  redirect-uri:     ${KAKAO_REDIRECT_URI:}
  auth-uri:         ${KAKAO_AUTH_URI:https://kauth.kakao.com/oauth/authorize}
  token-uri:        ${KAKAO_TOKEN_URI:https://kauth.kakao.com/oauth/token}
  user-info-uri:    ${KAKAO_USER_INFO_URI:https://kapi.kakao.com/v2/user/me}
  admin-key:        ${KAKAO_ADMIN_KEY:}

swagger:
  server:
    local: http://localhost:8080
    prod: https://gundaero.kozow.com

logging:
  level:
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG