server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework
  shutdown: graceful

spring:
  application:
    name: gundaero-alley-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/appdb?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Seoul}
    username: ${SPRING_DATASOURCE_USERNAME:alley_dev}
    password: ${SPRING_DATASOURCE_PASSWORD:devpass104}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}  # 비밀번호

# Swagger/OpenAPI (dev만 ON)
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

# JWT
jwt:
  secret: ${JWT_SECRET:dev-secret}
  access-ttl: ${JWT_ACCESS_TOKEN_TTL:900}
  refresh-ttl: ${JWT_REFRESH_TOKEN_TTL:1209600}

# S3
aws:
  s3:
    bucket: ${S3_BUCKET:gundaero-alley-dev-bucket}
    region: ${S3_REGION:ap-northeast-2}
